name: Component Library Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
            node-version: "14.x"
      
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
            node-version: "14.x"
      
      - name: Install
        run: yarn install

      - name: Build Stories
        run: yarn build-storybook
      
      - name: Deploy app 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
