name: Component Library Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build Stories
        run: yarn build-storybook
      - name: Deploy app 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
